### ISSUE TITLE
Content area width not always max-width

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/ae-template#41]
if column width not equal to 12 then the width does not fill the available space.
![right-gap](https://cloud.githubusercontent.com/assets/1850089/5696495/31efbcd6-9999-11e4-94c6-f495d7c65cf1.jpg)
![gap-dual](https://cloud.githubusercontent.com/assets/1850089/5696494/31ef3a5e-9999-11e4-9b8f-904d69a7caf5.jpg)
![gap-left](https://cloud.githubusercontent.com/assets/1850089/5696493/31eed2c6-9999-11e4-9783-d1a27233ea59.jpg)

**Comment by erikflowers** [comment]
Really hard to say without seeing some live code I can inspect though. Is there a little live version somewhere?

**Comment by N6REJ** [comment]
I sent an email and here is the video for http://git.jowwow.net <iframe class="tscplayer_inline embeddedObject" name="tsc_player" scrolling="no" frameborder="0" type="text/html" style="overflow:hidden;" src="http://www.screencast.com/users/N6REJ/folders/Default/media/3fc23e12-d0f5-4128-895e-a3baf6ae5823/embed" height="576" width="1024" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

**Comment by erikflowers** [comment]
ok. So what you're trying to do isn't real easy with Bootstrap. I know what you want - the shadow part around the content, with the gutter between. But you also want it to touch the edges. This can't work with Bootstrap unmodified since Bootstrap columns try to keep your content from the edges of the container/browser. So in your example, the main content area is correctly contained in the col-md-9. 

But on the col-md-9, you have the shadow applied to an interior div. But on the col-md-3, you have the shadow applied to the column itself, which is why it touches the right edge of the main page. But if you did that with the col-md-9, they would touch in the middle. 

What is going on here is that the main content area in the col-sm-9 is the only one set up to work with the grid. So just copy the same theory there to the rest.

So essentially - to do what you want, all of your shadowed boxes need to be contained inside of a column, meaning your header, nav, and breadcrumb bar need to be inside a col-md-12, and move the box shadow outline on your right side box to an interior div.

This is the only way to get the effect you want with Bootstraps default grid. You shouldn't really apply CSS to any of the col-*-* classes, it should just be there for containment. All your styled divs and such should be inside. If you tweak the design to have each of your horizontal modules in a col-md-12, and then put the shadow content inside those divs.
 
![screen shot 2015-01-16 at 9 15 28 am](https://cloud.githubusercontent.com/assets/913115/5780632/04433710-9d61-11e4-8780-c170b2a5993a.png)
this will all work.

**Comment by N6REJ** [comment]
Thanks erik, its going to take me a day or two to digest what you've 
just told me....
I'll start by removing the col- in css and remove any width changes I 
made in css.
I love the 3d look I accidentally created as it totally breaks the "i 
can tell its BS in 3 seconds" attitude.  The people in Joomla that I 
work with ( I'm on the joomla bug squad ) couldn't tell it was the 
default protostar bs2 template when I did this with it. Now I'm trying 
to do the same with BS3
I was able to create a BS3 contact form for Joomla 
http://git.jowwow.net/index.php?option=com_contact&view=contact&id=1&Itemid=103 
but I can't figure out where the tiny 2px bottom gap in message text 
area is coming from.  Nor where the big whitespace on the checkbox is from
I'd love your feedback on what you think of its look.
Also any other recommendations you'd make or styling comments on the 
template as a whole would be greatly appreciated.. I know i'm horrible @ 
design.

Bear
p.s. Thanks for contributing your time to the Open Source world.  I 
appreciate it, if your ever in Ponca City OK i'll buy you a drink.

**Comment by erikflowers** [comment]
The whitespace on the checkbox is under a bunch of styles, namely

.form-horizontal .checkbox has padding-top 11px
.form-control has padding 10px 15px

.form-control also has a background of white

you probably want to change it really specifically, like this:

```
.form-control.checkbox {
background-color: transparent;
}
```

![screen shot 2015-01-16 at 3 28 50 pm](https://cloud.githubusercontent.com/assets/913115/5786082/61c8921c-9d94-11e4-8b26-4cea437ce399.png)


There is sooo much that goes on in these Joomla templates though that unless you really know the theme and CSS, it's a nightmare to change. 


As for a 2px gap, I don't see that.

**Comment by N6REJ** [comment]
I started with http://demov3.joostrap.com/ and started tweaking it to 
make it use dark bootswatches ( though really it could use any )  and 
adding my customized swatch.  Sadly they took my alpha stage work and 
released it, almost line by line, as their own 
http://jooswatch.joostrap.com/ without even a acknowledgement that 90% 
of the "fixes"/"changes" came from me.
but I'm doing more tweaking and "fixing" to remove the rest of their 
bugs and enhance its looks / function.  Like this contact form was the 
standard BS2 controls and I've changed mine so its all BS3.
as you see on git I have 51 issues i'm working on/have worked on at this 
point.
the gap I'm speaking of is

your right in that it can be a lot of work to "tweak it"   I've spent 
well over 200 man hours so far
Bear
